theme: jekyll-theme-slate
include: ['_pages', '_redirect']
description: > # this means to ignore newlines until "baseurl:"
    this is my website. thanks for visiting.
    this is where i do some things sometimes.
url: ""
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-redirect-from
